export declare const bodyText: string;
export declare const buttons: string;
export declare const h1: string;
export declare const h2: string;
export declare const h3: string;
export declare const h4: string;
export declare const page: string;
export declare const smallText: string;
export declare const uppercase: string;
